version: '3'

services:
  web:
    image: 127.0.0.1:5000/swarm-ainur
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - swarm-pg
  swarm-pg:
    container_name: swarm-pg
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zzz
      - POSTGRES_DB=swarm_db